### PR TITLE
Fixed package.json issues 

### PR DESCRIPTION
**Pull request by raghavpuri**
Fixed the version number issue by adding it in the .JSON file

### CODE REVIEW

**Comment by agentmilindu** [comment]
Fixes #7

**Comment by agentmilindu** [comment]
@raghavpuri Let's add the following also,

-description
-keywords
-bugs
-licenses
-author,
-contributors,
-repository
-homepage
-engines

**Comment by raghavpuri** [comment]
Done :)

**Comment by Thuan2000** [comment]
Thank you raghavpuri ;) , happy new year!

**Comment by raghavpuri** [comment]
Happy New Year @Thuan2000  :)

**Pull request merged**
